#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam state=floating center=on follow=on border=off
~/.config/polybar/launch.sh &

setxkbmap tr &
picom --experimental-backends &
exec bspwm &
nitrogen --restore &
